pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Hello From Github"
            }
        }
        stage('Test') {
            steps {
                echo "Hello From Github test"
            }
            post {
                always {
                    echo "Hello From Github post"
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "Hello From Github Deliver"
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
        stage('Post Complete') {
            steps {
                echo 'Job Completed Yes!'
            }
        }
    }
}
