pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Hello From Github"
            }
        }
        stage('Test') {
            steps {
                echo "Hello From Github test"
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
